export const ufs = [
  {
    id: 11,
    sigla: 'RO',
    nome: 'Rondônia',
    regiao: {
      id: 1,
      sigla: 'N',
      nome: 'Norte',
    },
  },
  {
    id: 12,
    sigla: 'AC',
    nome: 'Acre',
    regiao: {
      id: 1,
      sigla: 'N',
      nome: 'Norte',
    },
  },
  {
    id: 13,
    sigla: 'AM',
    nome: 'Amazonas',
    regiao: {
      id: 1,
      sigla: 'N',
      nome: 'Norte',
    },
  },
  {
    id: 14,
    sigla: 'RR',
    nome: 'Roraima',
    regiao: {
      id: 1,
      sigla: 'N',
      nome: 'Norte',
    },
  },
  {
    id: 15,
    sigla: 'PA',
    nome: 'Pará',
    regiao: {
      id: 1,
      sigla: 'N',
      nome: 'Norte',
    },
  },
  {
    id: 16,
    sigla: 'AP',
    nome: 'Amapá',
    regiao: {
      id: 1,
      sigla: 'N',
      nome: 'Norte',
    },
  },
  {
    id: 17,
    sigla: 'TO',
    nome: 'Tocantins',
    regiao: {
      id: 1,
      sigla: 'N',
      nome: 'Norte',
    },
  },
  {
    id: 21,
    sigla: 'MA',
    nome: 'Maranhão',
    regiao: {
      id: 2,
      sigla: 'NE',
      nome: 'Nordeste',
    },
  },
  {
    id: 22,
    sigla: 'PI',
    nome: 'Piauí',
    regiao: {
      id: 2,
      sigla: 'NE',
      nome: 'Nordeste',
    },
  },
  {
    id: 23,
    sigla: 'CE',
    nome: 'Ceará',
    regiao: {
      id: 2,
      sigla: 'NE',
      nome: 'Nordeste',
    },
  },
  {
    id: 24,
    sigla: 'RN',
    nome: 'Rio Grande do Norte',
    regiao: {
      id: 2,
      sigla: 'NE',
      nome: 'Nordeste',
    },
  },
  {
    id: 25,
    sigla: 'PB',
    nome: 'Paraíba',
    regiao: {
      id: 2,
      sigla: 'NE',
      nome: 'Nordeste',
    },
  },
  {
    id: 26,
    sigla: 'PE',
    nome: 'Pernambuco',
    regiao: {
      id: 2,
      sigla: 'NE',
      nome: 'Nordeste',
    },
  },
  {
    id: 27,
    sigla: 'AL',
    nome: 'Alagoas',
    regiao: {
      id: 2,
      sigla: 'NE',
      nome: 'Nordeste',
    },
  },
  {
    id: 28,
    sigla: 'SE',
    nome: 'Sergipe',
    regiao: {
      id: 2,
      sigla: 'NE',
      nome: 'Nordeste',
    },
  },
  {
    id: 29,
    sigla: 'BA',
    nome: 'Bahia',
    regiao: {
      id: 2,
      sigla: 'NE',
      nome: 'Nordeste',
    },
  },
  {
    id: 31,
    sigla: 'MG',
    nome: 'Minas Gerais',
    regiao: {
      id: 3,
      sigla: 'SE',
      nome: 'Sudeste',
    },
  },
  {
    id: 32,
    sigla: 'ES',
    nome: 'Espírito Santo',
    regiao: {
      id: 3,
      sigla: 'SE',
      nome: 'Sudeste',
    },
  },
  {
    id: 33,
    sigla: 'RJ',
    nome: 'Rio de Janeiro',
    regiao: {
      id: 3,
      sigla: 'SE',
      nome: 'Sudeste',
    },
  },
  {
    id: 35,
    sigla: 'SP',
    nome: 'São Paulo',
    regiao: {
      id: 3,
      sigla: 'SE',
      nome: 'Sudeste',
    },
  },
  {
    id: 41,
    sigla: 'PR',
    nome: 'Paraná',
    regiao: {
      id: 4,
      sigla: 'S',
      nome: 'Sul',
    },
  },
  {
    id: 42,
    sigla: 'SC',
    nome: 'Santa Catarina',
    regiao: {
      id: 4,
      sigla: 'S',
      nome: 'Sul',
    },
  },
  {
    id: 43,
    sigla: 'RS',
    nome: 'Rio Grande do Sul',
    regiao: {
      id: 4,
      sigla: 'S',
      nome: 'Sul',
    },
  },
  {
    id: 50,
    sigla: 'MS',
    nome: 'Mato Grosso do Sul',
    regiao: {
      id: 5,
      sigla: 'CO',
      nome: 'Centro-Oeste',
    },
  },
  {
    id: 51,
    sigla: 'MT',
    nome: 'Mato Grosso',
    regiao: {
      id: 5,
      sigla: 'CO',
      nome: 'Centro-Oeste',
    },
  },
  {
    id: 52,
    sigla: 'GO',
    nome: 'Goiás',
    regiao: {
      id: 5,
      sigla: 'CO',
      nome: 'Centro-Oeste',
    },
  },
  {
    id: 53,
    sigla: 'DF',
    nome: 'Distrito Federal',
    regiao: {
      id: 5,
      sigla: 'CO',
      nome: 'Centro-Oeste',
    },
  },
];

// export interface TCountry {
//   'pais-M49': number;
//   'pais-ISO-ALPHA-2': string;
//   'pais-ISO-ALPHA-3': string;
//   'pais-nome': string;
//   'regiao-intermediaria-M49': null;
//   'regiao-intermediaria-nome': null;
//   'sub-regiao-M49': number;
//   'sub-regiao-nome': string;
//   'regiao-M49': number;
//   'regiao-nome': string;
// }

export const countryes = [
  {
    'pais-M49': 4,
    'pais-ISO-ALPHA-2': 'AF',
    'pais-ISO-ALPHA-3': 'AFG',
    'pais-nome': 'Afeganistão',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 34,
    'sub-regiao-nome': 'Ásia meridional (Sul da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 8,
    'pais-ISO-ALPHA-2': 'AL',
    'pais-ISO-ALPHA-3': 'ALB',
    'pais-nome': 'Albânia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 39,
    'sub-regiao-nome': 'Europa meridional  (Sul da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 12,
    'pais-ISO-ALPHA-2': 'DZ',
    'pais-ISO-ALPHA-3': 'DZA',
    'pais-nome': 'Argélia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 15,
    'sub-regiao-nome': 'África setentrional (Norte da África)',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 20,
    'pais-ISO-ALPHA-2': 'AD',
    'pais-ISO-ALPHA-3': 'AND',
    'pais-nome': 'Andorra',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 39,
    'sub-regiao-nome': 'Europa meridional  (Sul da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 24,
    'pais-ISO-ALPHA-2': 'AO',
    'pais-ISO-ALPHA-3': 'AGO',
    'pais-nome': 'Angola',
    'regiao-intermediaria-M49': 17,
    'regiao-intermediaria-nome': 'África central',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 28,
    'pais-ISO-ALPHA-2': 'AG',
    'pais-ISO-ALPHA-3': 'ATG',
    'pais-nome': 'Antígua e Barbuda',
    'regiao-intermediaria-M49': 29,
    'regiao-intermediaria-nome': 'Caribe',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 31,
    'pais-ISO-ALPHA-2': 'AZ',
    'pais-ISO-ALPHA-3': 'AZE',
    'pais-nome': 'Azerbaijão',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 32,
    'pais-ISO-ALPHA-2': 'AR',
    'pais-ISO-ALPHA-3': 'ARG',
    'pais-nome': 'Argentina',
    'regiao-intermediaria-M49': 5,
    'regiao-intermediaria-nome': 'América do sul',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 36,
    'pais-ISO-ALPHA-2': 'AU',
    'pais-ISO-ALPHA-3': 'AUS',
    'pais-nome': 'Austrália',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 53,
    'sub-regiao-nome': 'Austrália e Nova Zelândia',
    'regiao-M49': 9,
    'regiao-nome': 'Oceania',
  },
  {
    'pais-M49': 40,
    'pais-ISO-ALPHA-2': 'AT',
    'pais-ISO-ALPHA-3': 'AUT',
    'pais-nome': 'Áustria',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 155,
    'sub-regiao-nome': 'Europa ocidental (Oeste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 44,
    'pais-ISO-ALPHA-2': 'BS',
    'pais-ISO-ALPHA-3': 'BHS',
    'pais-nome': 'Bahamas',
    'regiao-intermediaria-M49': 29,
    'regiao-intermediaria-nome': 'Caribe',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 48,
    'pais-ISO-ALPHA-2': 'BH',
    'pais-ISO-ALPHA-3': 'BHR',
    'pais-nome': 'Barein',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 50,
    'pais-ISO-ALPHA-2': 'BD',
    'pais-ISO-ALPHA-3': 'BGD',
    'pais-nome': 'Bangladesh',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 34,
    'sub-regiao-nome': 'Ásia meridional (Sul da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 51,
    'pais-ISO-ALPHA-2': 'AM',
    'pais-ISO-ALPHA-3': 'ARM',
    'pais-nome': 'Armênia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 52,
    'pais-ISO-ALPHA-2': 'BB',
    'pais-ISO-ALPHA-3': 'BRB',
    'pais-nome': 'Barbados',
    'regiao-intermediaria-M49': 29,
    'regiao-intermediaria-nome': 'Caribe',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 56,
    'pais-ISO-ALPHA-2': 'BE',
    'pais-ISO-ALPHA-3': 'BEL',
    'pais-nome': 'Bélgica',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 155,
    'sub-regiao-nome': 'Europa ocidental (Oeste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 64,
    'pais-ISO-ALPHA-2': 'BT',
    'pais-ISO-ALPHA-3': 'BTN',
    'pais-nome': 'Butão',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 34,
    'sub-regiao-nome': 'Ásia meridional (Sul da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 68,
    'pais-ISO-ALPHA-2': 'BO',
    'pais-ISO-ALPHA-3': 'BOL',
    'pais-nome': 'Bolívia (Estado Plurinacional da)',
    'regiao-intermediaria-M49': 5,
    'regiao-intermediaria-nome': 'América do sul',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 70,
    'pais-ISO-ALPHA-2': 'BA',
    'pais-ISO-ALPHA-3': 'BIH',
    'pais-nome': 'Bósnia e Herzegovina',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 39,
    'sub-regiao-nome': 'Europa meridional  (Sul da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 72,
    'pais-ISO-ALPHA-2': 'BW',
    'pais-ISO-ALPHA-3': 'BWA',
    'pais-nome': 'Botsuana',
    'regiao-intermediaria-M49': 18,
    'regiao-intermediaria-nome': 'África meridional (Sul da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 76,
    'pais-ISO-ALPHA-2': 'BR',
    'pais-ISO-ALPHA-3': 'BRA',
    'pais-nome': 'Brasil',
    'regiao-intermediaria-M49': 5,
    'regiao-intermediaria-nome': 'América do sul',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 84,
    'pais-ISO-ALPHA-2': 'BZ',
    'pais-ISO-ALPHA-3': 'BLZ',
    'pais-nome': 'Belize',
    'regiao-intermediaria-M49': 13,
    'regiao-intermediaria-nome': 'América central',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 90,
    'pais-ISO-ALPHA-2': 'SB',
    'pais-ISO-ALPHA-3': 'SLB',
    'pais-nome': 'Ilhas Salomão',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 54,
    'sub-regiao-nome': 'Melanésia',
    'regiao-M49': 9,
    'regiao-nome': 'Oceania',
  },
  {
    'pais-M49': 96,
    'pais-ISO-ALPHA-2': 'BN',
    'pais-ISO-ALPHA-3': 'BRN',
    'pais-nome': 'Brunei',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 35,
    'sub-regiao-nome': 'Sudeste da Ásia',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 100,
    'pais-ISO-ALPHA-2': 'BG',
    'pais-ISO-ALPHA-3': 'BGR',
    'pais-nome': 'Bulgária',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 151,
    'sub-regiao-nome': 'Europa oriental (Leste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 104,
    'pais-ISO-ALPHA-2': 'MM',
    'pais-ISO-ALPHA-3': 'MMR',
    'pais-nome': 'Mianmar',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 35,
    'sub-regiao-nome': 'Sudeste da Ásia',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 108,
    'pais-ISO-ALPHA-2': 'BI',
    'pais-ISO-ALPHA-3': 'BDI',
    'pais-nome': 'Burundi',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 112,
    'pais-ISO-ALPHA-2': 'BY',
    'pais-ISO-ALPHA-3': 'BLR',
    'pais-nome': 'Belarus',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 151,
    'sub-regiao-nome': 'Europa oriental (Leste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 116,
    'pais-ISO-ALPHA-2': 'KH',
    'pais-ISO-ALPHA-3': 'KHM',
    'pais-nome': 'Camboja',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 35,
    'sub-regiao-nome': 'Sudeste da Ásia',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 120,
    'pais-ISO-ALPHA-2': 'CM',
    'pais-ISO-ALPHA-3': 'CMR',
    'pais-nome': 'Camarões',
    'regiao-intermediaria-M49': 17,
    'regiao-intermediaria-nome': 'África central',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 124,
    'pais-ISO-ALPHA-2': 'CA',
    'pais-ISO-ALPHA-3': 'CAN',
    'pais-nome': 'Canadá',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 21,
    'sub-regiao-nome': 'América do Norte',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 132,
    'pais-ISO-ALPHA-2': 'CV',
    'pais-ISO-ALPHA-3': 'CPV',
    'pais-nome': 'Cabo Verde',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 140,
    'pais-ISO-ALPHA-2': 'CF',
    'pais-ISO-ALPHA-3': 'CAF',
    'pais-nome': 'República Centro-Africana',
    'regiao-intermediaria-M49': 17,
    'regiao-intermediaria-nome': 'África central',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 144,
    'pais-ISO-ALPHA-2': 'LK',
    'pais-ISO-ALPHA-3': 'LKA',
    'pais-nome': 'Sri Lanka',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 34,
    'sub-regiao-nome': 'Ásia meridional (Sul da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 148,
    'pais-ISO-ALPHA-2': 'TD',
    'pais-ISO-ALPHA-3': 'TCD',
    'pais-nome': 'Chade',
    'regiao-intermediaria-M49': 17,
    'regiao-intermediaria-nome': 'África central',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 152,
    'pais-ISO-ALPHA-2': 'CL',
    'pais-ISO-ALPHA-3': 'CHL',
    'pais-nome': 'Chile',
    'regiao-intermediaria-M49': 5,
    'regiao-intermediaria-nome': 'América do sul',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 156,
    'pais-ISO-ALPHA-2': 'CN',
    'pais-ISO-ALPHA-3': 'CHN',
    'pais-nome': 'China',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 30,
    'sub-regiao-nome': 'Ásia oriental (Leste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 170,
    'pais-ISO-ALPHA-2': 'CO',
    'pais-ISO-ALPHA-3': 'COL',
    'pais-nome': 'Colômbia',
    'regiao-intermediaria-M49': 5,
    'regiao-intermediaria-nome': 'América do sul',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 174,
    'pais-ISO-ALPHA-2': 'KM',
    'pais-ISO-ALPHA-3': 'COM',
    'pais-nome': 'Comores',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 178,
    'pais-ISO-ALPHA-2': 'CG',
    'pais-ISO-ALPHA-3': 'COG',
    'pais-nome': 'Congo',
    'regiao-intermediaria-M49': 17,
    'regiao-intermediaria-nome': 'África central',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 180,
    'pais-ISO-ALPHA-2': 'CD',
    'pais-ISO-ALPHA-3': 'COD',
    'pais-nome': 'República Democrática do Congo',
    'regiao-intermediaria-M49': 17,
    'regiao-intermediaria-nome': 'África central',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 188,
    'pais-ISO-ALPHA-2': 'CR',
    'pais-ISO-ALPHA-3': 'CRI',
    'pais-nome': 'Costa Rica',
    'regiao-intermediaria-M49': 13,
    'regiao-intermediaria-nome': 'América central',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 191,
    'pais-ISO-ALPHA-2': 'HR',
    'pais-ISO-ALPHA-3': 'HRV',
    'pais-nome': 'Croácia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 39,
    'sub-regiao-nome': 'Europa meridional  (Sul da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 192,
    'pais-ISO-ALPHA-2': 'CU',
    'pais-ISO-ALPHA-3': 'CUB',
    'pais-nome': 'Cuba',
    'regiao-intermediaria-M49': 29,
    'regiao-intermediaria-nome': 'Caribe',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 196,
    'pais-ISO-ALPHA-2': 'CY',
    'pais-ISO-ALPHA-3': 'CYP',
    'pais-nome': 'Chipre',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 203,
    'pais-ISO-ALPHA-2': 'CZ',
    'pais-ISO-ALPHA-3': 'CZE',
    'pais-nome': 'República Tcheca',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 151,
    'sub-regiao-nome': 'Europa oriental (Leste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 204,
    'pais-ISO-ALPHA-2': 'BJ',
    'pais-ISO-ALPHA-3': 'BEN',
    'pais-nome': 'Benin',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 208,
    'pais-ISO-ALPHA-2': 'DK',
    'pais-ISO-ALPHA-3': 'DNK',
    'pais-nome': 'Dinamarca',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 154,
    'sub-regiao-nome': 'Europa setentrional (Norte da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 212,
    'pais-ISO-ALPHA-2': 'DM',
    'pais-ISO-ALPHA-3': 'DMA',
    'pais-nome': 'Dominica',
    'regiao-intermediaria-M49': 29,
    'regiao-intermediaria-nome': 'Caribe',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 214,
    'pais-ISO-ALPHA-2': 'DO',
    'pais-ISO-ALPHA-3': 'DOM',
    'pais-nome': 'República Dominicana',
    'regiao-intermediaria-M49': 29,
    'regiao-intermediaria-nome': 'Caribe',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 218,
    'pais-ISO-ALPHA-2': 'EC',
    'pais-ISO-ALPHA-3': 'ECU',
    'pais-nome': 'Equador',
    'regiao-intermediaria-M49': 5,
    'regiao-intermediaria-nome': 'América do sul',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 222,
    'pais-ISO-ALPHA-2': 'SV',
    'pais-ISO-ALPHA-3': 'SLV',
    'pais-nome': 'El Salvador',
    'regiao-intermediaria-M49': 13,
    'regiao-intermediaria-nome': 'América central',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 226,
    'pais-ISO-ALPHA-2': 'GQ',
    'pais-ISO-ALPHA-3': 'GNQ',
    'pais-nome': 'Guiné Equatorial',
    'regiao-intermediaria-M49': 17,
    'regiao-intermediaria-nome': 'África central',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 231,
    'pais-ISO-ALPHA-2': 'ET',
    'pais-ISO-ALPHA-3': 'ETH',
    'pais-nome': 'Etiópia',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 232,
    'pais-ISO-ALPHA-2': 'ER',
    'pais-ISO-ALPHA-3': 'ERI',
    'pais-nome': 'Eritreia',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 233,
    'pais-ISO-ALPHA-2': 'EE',
    'pais-ISO-ALPHA-3': 'EST',
    'pais-nome': 'Estônia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 154,
    'sub-regiao-nome': 'Europa setentrional (Norte da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 242,
    'pais-ISO-ALPHA-2': 'FJ',
    'pais-ISO-ALPHA-3': 'FJI',
    'pais-nome': 'Fiji',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 54,
    'sub-regiao-nome': 'Melanésia',
    'regiao-M49': 9,
    'regiao-nome': 'Oceania',
  },
  {
    'pais-M49': 246,
    'pais-ISO-ALPHA-2': 'FI',
    'pais-ISO-ALPHA-3': 'FIN',
    'pais-nome': 'Finlândia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 154,
    'sub-regiao-nome': 'Europa setentrional (Norte da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 250,
    'pais-ISO-ALPHA-2': 'FR',
    'pais-ISO-ALPHA-3': 'FRA',
    'pais-nome': 'França',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 155,
    'sub-regiao-nome': 'Europa ocidental (Oeste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 262,
    'pais-ISO-ALPHA-2': 'DJ',
    'pais-ISO-ALPHA-3': 'DJI',
    'pais-nome': 'Djibouti',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 266,
    'pais-ISO-ALPHA-2': 'GA',
    'pais-ISO-ALPHA-3': 'GAB',
    'pais-nome': 'Gabão',
    'regiao-intermediaria-M49': 17,
    'regiao-intermediaria-nome': 'África central',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 268,
    'pais-ISO-ALPHA-2': 'GE',
    'pais-ISO-ALPHA-3': 'GEO',
    'pais-nome': 'Geórgia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 270,
    'pais-ISO-ALPHA-2': 'GM',
    'pais-ISO-ALPHA-3': 'GMB',
    'pais-nome': 'Gâmbia',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 276,
    'pais-ISO-ALPHA-2': 'DE',
    'pais-ISO-ALPHA-3': 'DEU',
    'pais-nome': 'Alemanha',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 155,
    'sub-regiao-nome': 'Europa ocidental (Oeste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 288,
    'pais-ISO-ALPHA-2': 'GH',
    'pais-ISO-ALPHA-3': 'GHA',
    'pais-nome': 'Gana',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 296,
    'pais-ISO-ALPHA-2': 'KI',
    'pais-ISO-ALPHA-3': 'KIR',
    'pais-nome': 'Kiribati',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 57,
    'sub-regiao-nome': 'Micronésia',
    'regiao-M49': 9,
    'regiao-nome': 'Oceania',
  },
  {
    'pais-M49': 300,
    'pais-ISO-ALPHA-2': 'GR',
    'pais-ISO-ALPHA-3': 'GRC',
    'pais-nome': 'Grécia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 39,
    'sub-regiao-nome': 'Europa meridional  (Sul da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 308,
    'pais-ISO-ALPHA-2': 'GD',
    'pais-ISO-ALPHA-3': 'GRD',
    'pais-nome': 'Granada',
    'regiao-intermediaria-M49': 29,
    'regiao-intermediaria-nome': 'Caribe',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 320,
    'pais-ISO-ALPHA-2': 'GT',
    'pais-ISO-ALPHA-3': 'GTM',
    'pais-nome': 'Guatemala',
    'regiao-intermediaria-M49': 13,
    'regiao-intermediaria-nome': 'América central',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 324,
    'pais-ISO-ALPHA-2': 'GN',
    'pais-ISO-ALPHA-3': 'GIN',
    'pais-nome': 'Guiné',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 328,
    'pais-ISO-ALPHA-2': 'GY',
    'pais-ISO-ALPHA-3': 'GUY',
    'pais-nome': 'Guiana',
    'regiao-intermediaria-M49': 5,
    'regiao-intermediaria-nome': 'América do sul',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 332,
    'pais-ISO-ALPHA-2': 'HT',
    'pais-ISO-ALPHA-3': 'HTI',
    'pais-nome': 'Haiti',
    'regiao-intermediaria-M49': 29,
    'regiao-intermediaria-nome': 'Caribe',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 340,
    'pais-ISO-ALPHA-2': 'HN',
    'pais-ISO-ALPHA-3': 'HND',
    'pais-nome': 'Honduras',
    'regiao-intermediaria-M49': 13,
    'regiao-intermediaria-nome': 'América central',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 348,
    'pais-ISO-ALPHA-2': 'HU',
    'pais-ISO-ALPHA-3': 'HUN',
    'pais-nome': 'Hungria',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 151,
    'sub-regiao-nome': 'Europa oriental (Leste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 352,
    'pais-ISO-ALPHA-2': 'IS',
    'pais-ISO-ALPHA-3': 'ISL',
    'pais-nome': 'Islândia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 154,
    'sub-regiao-nome': 'Europa setentrional (Norte da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 356,
    'pais-ISO-ALPHA-2': 'IN',
    'pais-ISO-ALPHA-3': 'IND',
    'pais-nome': 'Índia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 34,
    'sub-regiao-nome': 'Ásia meridional (Sul da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 360,
    'pais-ISO-ALPHA-2': 'ID',
    'pais-ISO-ALPHA-3': 'IDN',
    'pais-nome': 'Indonésia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 35,
    'sub-regiao-nome': 'Sudeste da Ásia',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 364,
    'pais-ISO-ALPHA-2': 'IR',
    'pais-ISO-ALPHA-3': 'IRN',
    'pais-nome': 'Irã (República Islâmica do)',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 34,
    'sub-regiao-nome': 'Ásia meridional (Sul da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 368,
    'pais-ISO-ALPHA-2': 'IQ',
    'pais-ISO-ALPHA-3': 'IRQ',
    'pais-nome': 'Iraque',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 372,
    'pais-ISO-ALPHA-2': 'IE',
    'pais-ISO-ALPHA-3': 'IRL',
    'pais-nome': 'Irlanda',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 154,
    'sub-regiao-nome': 'Europa setentrional (Norte da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 376,
    'pais-ISO-ALPHA-2': 'IL',
    'pais-ISO-ALPHA-3': 'ISR',
    'pais-nome': 'Israel',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 380,
    'pais-ISO-ALPHA-2': 'IT',
    'pais-ISO-ALPHA-3': 'ITA',
    'pais-nome': 'Itália',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 39,
    'sub-regiao-nome': 'Europa meridional  (Sul da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 384,
    'pais-ISO-ALPHA-2': 'CI',
    'pais-ISO-ALPHA-3': 'CIV',
    'pais-nome': 'Costa do Marfim',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 388,
    'pais-ISO-ALPHA-2': 'JM',
    'pais-ISO-ALPHA-3': 'JAM',
    'pais-nome': 'Jamaica',
    'regiao-intermediaria-M49': 29,
    'regiao-intermediaria-nome': 'Caribe',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 392,
    'pais-ISO-ALPHA-2': 'JP',
    'pais-ISO-ALPHA-3': 'JPN',
    'pais-nome': 'Japão',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 30,
    'sub-regiao-nome': 'Ásia oriental (Leste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 398,
    'pais-ISO-ALPHA-2': 'KZ',
    'pais-ISO-ALPHA-3': 'KAZ',
    'pais-nome': 'Cazaquistão',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 143,
    'sub-regiao-nome': 'Ásia central',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 400,
    'pais-ISO-ALPHA-2': 'JO',
    'pais-ISO-ALPHA-3': 'JOR',
    'pais-nome': 'Jordânia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 404,
    'pais-ISO-ALPHA-2': 'KE',
    'pais-ISO-ALPHA-3': 'KEN',
    'pais-nome': 'Quênia',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 408,
    'pais-ISO-ALPHA-2': 'KP',
    'pais-ISO-ALPHA-3': 'PRK',
    'pais-nome': 'República Popular Democrática da Coreia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 30,
    'sub-regiao-nome': 'Ásia oriental (Leste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 410,
    'pais-ISO-ALPHA-2': 'KR',
    'pais-ISO-ALPHA-3': 'KOR',
    'pais-nome': 'República da Coreia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 30,
    'sub-regiao-nome': 'Ásia oriental (Leste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 414,
    'pais-ISO-ALPHA-2': 'KW',
    'pais-ISO-ALPHA-3': 'KWT',
    'pais-nome': 'Kuwait',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 417,
    'pais-ISO-ALPHA-2': 'KG',
    'pais-ISO-ALPHA-3': 'KGZ',
    'pais-nome': 'Quirguistão',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 143,
    'sub-regiao-nome': 'Ásia central',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 418,
    'pais-ISO-ALPHA-2': 'LA',
    'pais-ISO-ALPHA-3': 'LAO',
    'pais-nome': 'República Democrática Popular do Laos',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 35,
    'sub-regiao-nome': 'Sudeste da Ásia',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 422,
    'pais-ISO-ALPHA-2': 'LB',
    'pais-ISO-ALPHA-3': 'LBN',
    'pais-nome': 'Líbano',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 426,
    'pais-ISO-ALPHA-2': 'LS',
    'pais-ISO-ALPHA-3': 'LSO',
    'pais-nome': 'Lesoto',
    'regiao-intermediaria-M49': 18,
    'regiao-intermediaria-nome': 'África meridional (Sul da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 428,
    'pais-ISO-ALPHA-2': 'LV',
    'pais-ISO-ALPHA-3': 'LVA',
    'pais-nome': 'Letônia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 154,
    'sub-regiao-nome': 'Europa setentrional (Norte da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 430,
    'pais-ISO-ALPHA-2': 'LR',
    'pais-ISO-ALPHA-3': 'LBR',
    'pais-nome': 'Libéria',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 434,
    'pais-ISO-ALPHA-2': 'LY',
    'pais-ISO-ALPHA-3': 'LBY',
    'pais-nome': 'Líbia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 15,
    'sub-regiao-nome': 'África setentrional (Norte da África)',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 438,
    'pais-ISO-ALPHA-2': 'LI',
    'pais-ISO-ALPHA-3': 'LIE',
    'pais-nome': 'Liechtenstein',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 155,
    'sub-regiao-nome': 'Europa ocidental (Oeste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 440,
    'pais-ISO-ALPHA-2': 'LT',
    'pais-ISO-ALPHA-3': 'LTU',
    'pais-nome': 'Lituânia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 154,
    'sub-regiao-nome': 'Europa setentrional (Norte da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 442,
    'pais-ISO-ALPHA-2': 'LU',
    'pais-ISO-ALPHA-3': 'LUX',
    'pais-nome': 'Luxemburgo',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 155,
    'sub-regiao-nome': 'Europa ocidental (Oeste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 450,
    'pais-ISO-ALPHA-2': 'MG',
    'pais-ISO-ALPHA-3': 'MDG',
    'pais-nome': 'Madagascar',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 454,
    'pais-ISO-ALPHA-2': 'MW',
    'pais-ISO-ALPHA-3': 'MWI',
    'pais-nome': 'Malauí',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 458,
    'pais-ISO-ALPHA-2': 'MY',
    'pais-ISO-ALPHA-3': 'MYS',
    'pais-nome': 'Malásia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 35,
    'sub-regiao-nome': 'Sudeste da Ásia',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 462,
    'pais-ISO-ALPHA-2': 'MV',
    'pais-ISO-ALPHA-3': 'MDV',
    'pais-nome': 'Maldivas',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 34,
    'sub-regiao-nome': 'Ásia meridional (Sul da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 466,
    'pais-ISO-ALPHA-2': 'ML',
    'pais-ISO-ALPHA-3': 'MLI',
    'pais-nome': 'Mali',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 470,
    'pais-ISO-ALPHA-2': 'MT',
    'pais-ISO-ALPHA-3': 'MLT',
    'pais-nome': 'Malta',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 39,
    'sub-regiao-nome': 'Europa meridional  (Sul da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 478,
    'pais-ISO-ALPHA-2': 'MR',
    'pais-ISO-ALPHA-3': 'MRT',
    'pais-nome': 'Mauritânia',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 480,
    'pais-ISO-ALPHA-2': 'MU',
    'pais-ISO-ALPHA-3': 'MUS',
    'pais-nome': 'Maurício',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 484,
    'pais-ISO-ALPHA-2': 'MX',
    'pais-ISO-ALPHA-3': 'MEX',
    'pais-nome': 'México',
    'regiao-intermediaria-M49': 13,
    'regiao-intermediaria-nome': 'América central',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 492,
    'pais-ISO-ALPHA-2': 'MC',
    'pais-ISO-ALPHA-3': 'MCO',
    'pais-nome': 'Mônaco',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 155,
    'sub-regiao-nome': 'Europa ocidental (Oeste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 496,
    'pais-ISO-ALPHA-2': 'MN',
    'pais-ISO-ALPHA-3': 'MNG',
    'pais-nome': 'Mongólia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 30,
    'sub-regiao-nome': 'Ásia oriental (Leste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 498,
    'pais-ISO-ALPHA-2': 'MD',
    'pais-ISO-ALPHA-3': 'MDA',
    'pais-nome': 'Moldávia (República da)',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 151,
    'sub-regiao-nome': 'Europa oriental (Leste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 499,
    'pais-ISO-ALPHA-2': 'ME',
    'pais-ISO-ALPHA-3': 'MNE',
    'pais-nome': 'Montenegro',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 39,
    'sub-regiao-nome': 'Europa meridional  (Sul da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 504,
    'pais-ISO-ALPHA-2': 'MA',
    'pais-ISO-ALPHA-3': 'MAR',
    'pais-nome': 'Marrocos',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 15,
    'sub-regiao-nome': 'África setentrional (Norte da África)',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 508,
    'pais-ISO-ALPHA-2': 'MZ',
    'pais-ISO-ALPHA-3': 'MOZ',
    'pais-nome': 'Moçambique',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 512,
    'pais-ISO-ALPHA-2': 'OM',
    'pais-ISO-ALPHA-3': 'OMN',
    'pais-nome': 'Omã',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 516,
    'pais-ISO-ALPHA-2': 'NA',
    'pais-ISO-ALPHA-3': 'NAM',
    'pais-nome': 'Namíbia',
    'regiao-intermediaria-M49': 18,
    'regiao-intermediaria-nome': 'África meridional (Sul da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 520,
    'pais-ISO-ALPHA-2': 'NR',
    'pais-ISO-ALPHA-3': 'NRU',
    'pais-nome': 'Nauru',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 57,
    'sub-regiao-nome': 'Micronésia',
    'regiao-M49': 9,
    'regiao-nome': 'Oceania',
  },
  {
    'pais-M49': 524,
    'pais-ISO-ALPHA-2': 'NP',
    'pais-ISO-ALPHA-3': 'NPL',
    'pais-nome': 'Nepal',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 34,
    'sub-regiao-nome': 'Ásia meridional (Sul da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 528,
    'pais-ISO-ALPHA-2': 'NL',
    'pais-ISO-ALPHA-3': 'NLD',
    'pais-nome': 'Holanda',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 155,
    'sub-regiao-nome': 'Europa ocidental (Oeste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 548,
    'pais-ISO-ALPHA-2': 'VU',
    'pais-ISO-ALPHA-3': 'VUT',
    'pais-nome': 'Vanuatu',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 54,
    'sub-regiao-nome': 'Melanésia',
    'regiao-M49': 9,
    'regiao-nome': 'Oceania',
  },
  {
    'pais-M49': 554,
    'pais-ISO-ALPHA-2': 'NZ',
    'pais-ISO-ALPHA-3': 'NZL',
    'pais-nome': 'Nova Zelândia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 53,
    'sub-regiao-nome': 'Austrália e Nova Zelândia',
    'regiao-M49': 9,
    'regiao-nome': 'Oceania',
  },
  {
    'pais-M49': 558,
    'pais-ISO-ALPHA-2': 'NI',
    'pais-ISO-ALPHA-3': 'NIC',
    'pais-nome': 'Nicarágua',
    'regiao-intermediaria-M49': 13,
    'regiao-intermediaria-nome': 'América central',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 562,
    'pais-ISO-ALPHA-2': 'NE',
    'pais-ISO-ALPHA-3': 'NER',
    'pais-nome': 'Niger',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 566,
    'pais-ISO-ALPHA-2': 'NG',
    'pais-ISO-ALPHA-3': 'NGA',
    'pais-nome': 'Nigéria',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 578,
    'pais-ISO-ALPHA-2': 'NO',
    'pais-ISO-ALPHA-3': 'NOR',
    'pais-nome': 'Noruega',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 154,
    'sub-regiao-nome': 'Europa setentrional (Norte da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 583,
    'pais-ISO-ALPHA-2': 'FM',
    'pais-ISO-ALPHA-3': 'FSM',
    'pais-nome': 'Micronésia (Estados Federados da)',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 57,
    'sub-regiao-nome': 'Micronésia',
    'regiao-M49': 9,
    'regiao-nome': 'Oceania',
  },
  {
    'pais-M49': 584,
    'pais-ISO-ALPHA-2': 'MH',
    'pais-ISO-ALPHA-3': 'MHL',
    'pais-nome': 'Ilhas Marshall',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 57,
    'sub-regiao-nome': 'Micronésia',
    'regiao-M49': 9,
    'regiao-nome': 'Oceania',
  },
  {
    'pais-M49': 585,
    'pais-ISO-ALPHA-2': 'PW',
    'pais-ISO-ALPHA-3': 'PLW',
    'pais-nome': 'Palau',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 57,
    'sub-regiao-nome': 'Micronésia',
    'regiao-M49': 9,
    'regiao-nome': 'Oceania',
  },
  {
    'pais-M49': 586,
    'pais-ISO-ALPHA-2': 'PK',
    'pais-ISO-ALPHA-3': 'PAK',
    'pais-nome': 'Paquistão',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 34,
    'sub-regiao-nome': 'Ásia meridional (Sul da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 591,
    'pais-ISO-ALPHA-2': 'PA',
    'pais-ISO-ALPHA-3': 'PAN',
    'pais-nome': 'Panamá',
    'regiao-intermediaria-M49': 13,
    'regiao-intermediaria-nome': 'América central',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 598,
    'pais-ISO-ALPHA-2': 'PG',
    'pais-ISO-ALPHA-3': 'PNG',
    'pais-nome': 'Papua Nova Guiné',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 54,
    'sub-regiao-nome': 'Melanésia',
    'regiao-M49': 9,
    'regiao-nome': 'Oceania',
  },
  {
    'pais-M49': 600,
    'pais-ISO-ALPHA-2': 'PY',
    'pais-ISO-ALPHA-3': 'PRY',
    'pais-nome': 'Paraguai',
    'regiao-intermediaria-M49': 5,
    'regiao-intermediaria-nome': 'América do sul',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 604,
    'pais-ISO-ALPHA-2': 'PE',
    'pais-ISO-ALPHA-3': 'PER',
    'pais-nome': 'Peru',
    'regiao-intermediaria-M49': 5,
    'regiao-intermediaria-nome': 'América do sul',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 608,
    'pais-ISO-ALPHA-2': 'PH',
    'pais-ISO-ALPHA-3': 'PHL',
    'pais-nome': 'Filipinas',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 35,
    'sub-regiao-nome': 'Sudeste da Ásia',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 616,
    'pais-ISO-ALPHA-2': 'PL',
    'pais-ISO-ALPHA-3': 'POL',
    'pais-nome': 'Polônia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 151,
    'sub-regiao-nome': 'Europa oriental (Leste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 620,
    'pais-ISO-ALPHA-2': 'PT',
    'pais-ISO-ALPHA-3': 'PRT',
    'pais-nome': 'Portugal',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 39,
    'sub-regiao-nome': 'Europa meridional  (Sul da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 624,
    'pais-ISO-ALPHA-2': 'GW',
    'pais-ISO-ALPHA-3': 'GNB',
    'pais-nome': 'Guiné-Bissau',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 626,
    'pais-ISO-ALPHA-2': 'TL',
    'pais-ISO-ALPHA-3': 'TLS',
    'pais-nome': 'Timor-Leste',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 35,
    'sub-regiao-nome': 'Sudeste da Ásia',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 634,
    'pais-ISO-ALPHA-2': 'QA',
    'pais-ISO-ALPHA-3': 'QAT',
    'pais-nome': 'Catar',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 642,
    'pais-ISO-ALPHA-2': 'RO',
    'pais-ISO-ALPHA-3': 'ROU',
    'pais-nome': 'Romênia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 151,
    'sub-regiao-nome': 'Europa oriental (Leste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 643,
    'pais-ISO-ALPHA-2': 'RU',
    'pais-ISO-ALPHA-3': 'RUS',
    'pais-nome': 'Federação da Rússia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 151,
    'sub-regiao-nome': 'Europa oriental (Leste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 646,
    'pais-ISO-ALPHA-2': 'RW',
    'pais-ISO-ALPHA-3': 'RWA',
    'pais-nome': 'Ruanda',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 659,
    'pais-ISO-ALPHA-2': 'KN',
    'pais-ISO-ALPHA-3': 'KNA',
    'pais-nome': 'São Cristóvão e Nevis',
    'regiao-intermediaria-M49': 29,
    'regiao-intermediaria-nome': 'Caribe',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 662,
    'pais-ISO-ALPHA-2': 'LC',
    'pais-ISO-ALPHA-3': 'LCA',
    'pais-nome': 'Santa Lúcia',
    'regiao-intermediaria-M49': 29,
    'regiao-intermediaria-nome': 'Caribe',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 670,
    'pais-ISO-ALPHA-2': 'VC',
    'pais-ISO-ALPHA-3': 'VCT',
    'pais-nome': 'São Vicente e Granadinas',
    'regiao-intermediaria-M49': 29,
    'regiao-intermediaria-nome': 'Caribe',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 674,
    'pais-ISO-ALPHA-2': 'SM',
    'pais-ISO-ALPHA-3': 'SMR',
    'pais-nome': 'San Marino',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 39,
    'sub-regiao-nome': 'Europa meridional  (Sul da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 678,
    'pais-ISO-ALPHA-2': 'ST',
    'pais-ISO-ALPHA-3': 'STP',
    'pais-nome': 'São Tomé e Príncipe',
    'regiao-intermediaria-M49': 17,
    'regiao-intermediaria-nome': 'África central',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 682,
    'pais-ISO-ALPHA-2': 'SA',
    'pais-ISO-ALPHA-3': 'SAU',
    'pais-nome': 'Arábia Saudita',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 686,
    'pais-ISO-ALPHA-2': 'SN',
    'pais-ISO-ALPHA-3': 'SEN',
    'pais-nome': 'Senegal',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 688,
    'pais-ISO-ALPHA-2': 'RS',
    'pais-ISO-ALPHA-3': 'SRB',
    'pais-nome': 'Sérvia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 39,
    'sub-regiao-nome': 'Europa meridional  (Sul da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 690,
    'pais-ISO-ALPHA-2': 'SC',
    'pais-ISO-ALPHA-3': 'SYC',
    'pais-nome': 'Seichelles',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 694,
    'pais-ISO-ALPHA-2': 'SL',
    'pais-ISO-ALPHA-3': 'SLE',
    'pais-nome': 'Serra Leoa',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 702,
    'pais-ISO-ALPHA-2': 'SG',
    'pais-ISO-ALPHA-3': 'SGP',
    'pais-nome': 'Singapura',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 35,
    'sub-regiao-nome': 'Sudeste da Ásia',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 703,
    'pais-ISO-ALPHA-2': 'SK',
    'pais-ISO-ALPHA-3': 'SVK',
    'pais-nome': 'Eslováquia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 151,
    'sub-regiao-nome': 'Europa oriental (Leste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 704,
    'pais-ISO-ALPHA-2': 'VN',
    'pais-ISO-ALPHA-3': 'VNM',
    'pais-nome': 'Vietnã',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 35,
    'sub-regiao-nome': 'Sudeste da Ásia',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 705,
    'pais-ISO-ALPHA-2': 'SI',
    'pais-ISO-ALPHA-3': 'SVN',
    'pais-nome': 'Eslovênia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 39,
    'sub-regiao-nome': 'Europa meridional  (Sul da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 706,
    'pais-ISO-ALPHA-2': 'SO',
    'pais-ISO-ALPHA-3': 'SOM',
    'pais-nome': 'Somália',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 710,
    'pais-ISO-ALPHA-2': 'ZA',
    'pais-ISO-ALPHA-3': 'ZAF',
    'pais-nome': 'África do Sul',
    'regiao-intermediaria-M49': 18,
    'regiao-intermediaria-nome': 'África meridional (Sul da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 716,
    'pais-ISO-ALPHA-2': 'ZW',
    'pais-ISO-ALPHA-3': 'ZWE',
    'pais-nome': 'Zimbábue',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 724,
    'pais-ISO-ALPHA-2': 'ES',
    'pais-ISO-ALPHA-3': 'ESP',
    'pais-nome': 'Espanha',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 39,
    'sub-regiao-nome': 'Europa meridional  (Sul da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 728,
    'pais-ISO-ALPHA-2': 'SS',
    'pais-ISO-ALPHA-3': 'SSD',
    'pais-nome': 'Sudão do Sul',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 729,
    'pais-ISO-ALPHA-2': 'SD',
    'pais-ISO-ALPHA-3': 'SDN',
    'pais-nome': 'Sudão',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 15,
    'sub-regiao-nome': 'África setentrional (Norte da África)',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 740,
    'pais-ISO-ALPHA-2': 'SR',
    'pais-ISO-ALPHA-3': 'SUR',
    'pais-nome': 'Suriname',
    'regiao-intermediaria-M49': 5,
    'regiao-intermediaria-nome': 'América do sul',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 748,
    'pais-ISO-ALPHA-2': 'SZ',
    'pais-ISO-ALPHA-3': 'SWZ',
    'pais-nome': 'Eswatini',
    'regiao-intermediaria-M49': 18,
    'regiao-intermediaria-nome': 'África meridional (Sul da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 752,
    'pais-ISO-ALPHA-2': 'SE',
    'pais-ISO-ALPHA-3': 'SWE',
    'pais-nome': 'Suécia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 154,
    'sub-regiao-nome': 'Europa setentrional (Norte da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 756,
    'pais-ISO-ALPHA-2': 'CH',
    'pais-ISO-ALPHA-3': 'CHE',
    'pais-nome': 'Suíça',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 155,
    'sub-regiao-nome': 'Europa ocidental (Oeste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 760,
    'pais-ISO-ALPHA-2': 'SY',
    'pais-ISO-ALPHA-3': 'SYR',
    'pais-nome': 'Síria',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 762,
    'pais-ISO-ALPHA-2': 'TJ',
    'pais-ISO-ALPHA-3': 'TJK',
    'pais-nome': 'Tadjiquistão',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 143,
    'sub-regiao-nome': 'Ásia central',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 764,
    'pais-ISO-ALPHA-2': 'TH',
    'pais-ISO-ALPHA-3': 'THA',
    'pais-nome': 'Tailândia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 35,
    'sub-regiao-nome': 'Sudeste da Ásia',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 768,
    'pais-ISO-ALPHA-2': 'TG',
    'pais-ISO-ALPHA-3': 'TGO',
    'pais-nome': 'Togo',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 776,
    'pais-ISO-ALPHA-2': 'TO',
    'pais-ISO-ALPHA-3': 'TON',
    'pais-nome': 'Tonga',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 61,
    'sub-regiao-nome': 'Polinésia',
    'regiao-M49': 9,
    'regiao-nome': 'Oceania',
  },
  {
    'pais-M49': 780,
    'pais-ISO-ALPHA-2': 'TT',
    'pais-ISO-ALPHA-3': 'TTO',
    'pais-nome': 'Trinidad e Tobago',
    'regiao-intermediaria-M49': 29,
    'regiao-intermediaria-nome': 'Caribe',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 784,
    'pais-ISO-ALPHA-2': 'AE',
    'pais-ISO-ALPHA-3': 'ARE',
    'pais-nome': 'Emirados Árabes Unidos',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 788,
    'pais-ISO-ALPHA-2': 'TN',
    'pais-ISO-ALPHA-3': 'TUN',
    'pais-nome': 'Tunísia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 15,
    'sub-regiao-nome': 'África setentrional (Norte da África)',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 792,
    'pais-ISO-ALPHA-2': 'TR',
    'pais-ISO-ALPHA-3': 'TUR',
    'pais-nome': 'Turquia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 795,
    'pais-ISO-ALPHA-2': 'TM',
    'pais-ISO-ALPHA-3': 'TKM',
    'pais-nome': 'Turcomenistão',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 143,
    'sub-regiao-nome': 'Ásia central',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 798,
    'pais-ISO-ALPHA-2': 'TV',
    'pais-ISO-ALPHA-3': 'TUV',
    'pais-nome': 'Tuvalu',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 61,
    'sub-regiao-nome': 'Polinésia',
    'regiao-M49': 9,
    'regiao-nome': 'Oceania',
  },
  {
    'pais-M49': 800,
    'pais-ISO-ALPHA-2': 'UG',
    'pais-ISO-ALPHA-3': 'UGA',
    'pais-nome': 'Uganda',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 804,
    'pais-ISO-ALPHA-2': 'UA',
    'pais-ISO-ALPHA-3': 'UKR',
    'pais-nome': 'Ucrânia',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 151,
    'sub-regiao-nome': 'Europa oriental (Leste da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 807,
    'pais-ISO-ALPHA-2': 'MK',
    'pais-ISO-ALPHA-3': 'MKD',
    'pais-nome': 'Macedônia do Norte',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 39,
    'sub-regiao-nome': 'Europa meridional  (Sul da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 818,
    'pais-ISO-ALPHA-2': 'EG',
    'pais-ISO-ALPHA-3': 'EGY',
    'pais-nome': 'Egito',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 15,
    'sub-regiao-nome': 'África setentrional (Norte da África)',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 826,
    'pais-ISO-ALPHA-2': 'GB',
    'pais-ISO-ALPHA-3': 'GBR',
    'pais-nome': 'Reino Unido da Grã-Bretanha e Irlanda do Norte',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 154,
    'sub-regiao-nome': 'Europa setentrional (Norte da Europa)',
    'regiao-M49': 150,
    'regiao-nome': 'Europa',
  },
  {
    'pais-M49': 834,
    'pais-ISO-ALPHA-2': 'TZ',
    'pais-ISO-ALPHA-3': 'TZA',
    'pais-nome': 'Tanzânia, República Unida da',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 840,
    'pais-ISO-ALPHA-2': 'US',
    'pais-ISO-ALPHA-3': 'USA',
    'pais-nome': 'Estados Unidos da América',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 21,
    'sub-regiao-nome': 'América do Norte',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 854,
    'pais-ISO-ALPHA-2': 'BF',
    'pais-ISO-ALPHA-3': 'BFA',
    'pais-nome': 'Burkina Faso',
    'regiao-intermediaria-M49': 11,
    'regiao-intermediaria-nome': 'África ocidental (Oeste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
  {
    'pais-M49': 858,
    'pais-ISO-ALPHA-2': 'UY',
    'pais-ISO-ALPHA-3': 'URY',
    'pais-nome': 'Uruguai',
    'regiao-intermediaria-M49': 5,
    'regiao-intermediaria-nome': 'América do sul',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 860,
    'pais-ISO-ALPHA-2': 'UZ',
    'pais-ISO-ALPHA-3': 'UZB',
    'pais-nome': 'Uzbequistão',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 143,
    'sub-regiao-nome': 'Ásia central',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 862,
    'pais-ISO-ALPHA-2': 'VE',
    'pais-ISO-ALPHA-3': 'VEN',
    'pais-nome': 'Venezuela (República Bolivariana da)',
    'regiao-intermediaria-M49': 5,
    'regiao-intermediaria-nome': 'América do sul',
    'sub-regiao-M49': 419,
    'sub-regiao-nome': 'América Latina e Caribe',
    'regiao-M49': 19,
    'regiao-nome': 'América',
  },
  {
    'pais-M49': 882,
    'pais-ISO-ALPHA-2': 'WS',
    'pais-ISO-ALPHA-3': 'WSM',
    'pais-nome': 'Samoa',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 61,
    'sub-regiao-nome': 'Polinésia',
    'regiao-M49': 9,
    'regiao-nome': 'Oceania',
  },
  {
    'pais-M49': 887,
    'pais-ISO-ALPHA-2': 'YE',
    'pais-ISO-ALPHA-3': 'YEM',
    'pais-nome': 'Iêmen',
    'regiao-intermediaria-M49': null,
    'regiao-intermediaria-nome': null,
    'sub-regiao-M49': 145,
    'sub-regiao-nome': 'Ásia ocidental  (Oeste da Ásia)',
    'regiao-M49': 142,
    'regiao-nome': 'Ásia',
  },
  {
    'pais-M49': 894,
    'pais-ISO-ALPHA-2': 'ZM',
    'pais-ISO-ALPHA-3': 'ZMB',
    'pais-nome': 'Zâmbia',
    'regiao-intermediaria-M49': 14,
    'regiao-intermediaria-nome': 'África oriental (Leste da África)',
    'sub-regiao-M49': 202,
    'sub-regiao-nome': 'África subsaariana',
    'regiao-M49': 2,
    'regiao-nome': 'África',
  },
];
